/*
  Warnings:

  - You are about to drop the column `id` on the `JobConfig` table. All the data in the column will be lost.
  - You are about to alter the column `category` on the `JobConfig` table. The data in that column will be cast from `String` to `String`. This cast may fail. Please make sure the data in the column can be cast.
  - You are about to alter the column `description` on the `JobConfig` table. The data in that column will be cast from `String` to `String`. This cast may fail. Please make sure the data in the column can be cast.
  - You are about to alter the column `jobCode` on the `JobConfig` table. The data in that column will be cast from `String` to `String`. This cast may fail. Please make sure the data in the column can be cast.
  - You are about to alter the column `jobName` on the `JobConfig` table. The data in that column will be cast from `String` to `String`. This cast may fail. Please make sure the data in the column can be cast.
  - Made the column `description` on table `JobConfig` required. This step will fail if there are existing NULL values in that column.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_JobConfig" (
    "jobID" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "jobCode" STRING(255) NOT NULL,
    "jobName" STRING(255) NOT NULL,
    "description" STRING(255) NOT NULL,
    "category" STRING(2) NOT NULL,
    "status" "JobStatus" NOT NULL DEFAULT 'ACT',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "JobConfig_pkey" PRIMARY KEY ("jobID")
);
DROP INDEX "JobConfig_jobCode_key";
INSERT INTO "_prisma_new_JobConfig" ("category","createdAt","description","jobCode","jobName","status","updatedAt") SELECT "category","createdAt","description","jobCode","jobName","status","updatedAt" FROM "JobConfig";
DROP TABLE "JobConfig" CASCADE;
ALTER TABLE "_prisma_new_JobConfig" RENAME TO "JobConfig";
CREATE UNIQUE INDEX "JobConfig_jobCode_key" ON "JobConfig"("jobCode");
